### ISSUE TITLE
Camera issues in Godhome

### ISSUE THREAD

**Issue by Hoo-Knows** [nickc01/WeaverCore#3]
Entering a pantheon then dying or dreamgating out of it causes the camera to become desynced. Tested with P1 and P5.
Before:
![20220514183519_1](https://user-images.githubusercontent.com/73412292/168453589-feac5e2a-ff04-45c4-b50e-1a295dd60ce5.jpg)
After:
![20220514183556_1](https://user-images.githubusercontent.com/73412292/168453599-67d60d0f-4131-480a-93a7-a4e6ee00c586.jpg)

This issue seems to have started after I fought Corrupted Kin, but I don't know what exactly the cause could be.

**Comment by nickc01** [comment]
Are you able to post your ModLog.txt and your Player.txt (could also be called Player.log)? It could tell me any error messages that are caused when the problem occurs. They should be located at:

**Windows**: `%APPDATA%\..\LocalLow\Team Cherry\Hollow Knight\`

**MacOS**: `~/Library/Application Support/unity.Team Cherry.Hollow Knight/`

**Linux**: `~/.config/unity3d/Team Cherry/Hollow Knight/`

Although, this could be an issue I already fixed, but haven't made an official release for it yet, because I noticed a similar bug also happens when I benchwarped into Godhome, and made a fix for it in the "development" branch

**Comment by Hoo-Knows** [comment]
Here's the ModLog.txt and Player.log:
[ModLog.txt](https://github.com/nickc01/WeaverCore/files/8694204/ModLog.txt)
[Player.log](https://github.com/nickc01/WeaverCore/files/8694205/Player.log)

**Comment by nickc01** [comment]
I updated WeaverCore and my other mods with a bugfix that should prevent the camera from breaking. Let me know if it works:

Inferno King Grimm : https://github.com/nickc01/Inferno-King-Grimm/releases/tag/v4.1.0.2
Corrupted Kin : https://github.com/nickc01/Corrupted-Kin/releases/tag/v1.2.0.1
WeaverCore : https://github.com/nickc01/WeaverCore/releases/tag/v1.0.1.0

**Comment by Hoo-Knows** [comment]
Unfortunately I'm still having the same issue. Here's the new ModLog.txt and Player.log:
[ModLog.txt](https://github.com/nickc01/WeaverCore/files/8703963/ModLog.txt)
[Player.log](https://github.com/nickc01/WeaverCore/files/8703964/Player.log)

**Comment by nickc01** [comment]
I unfortunately won't be able to look at it right now since I got some college work I also need to get done. I'll look more into the issue when I have some more time

**Comment by nickc01** [comment]
Alright, I think I found and fixed the issue after looking around for several hours. I also tested it myself by starting a pantheon and using the dreamgate to warp out, and the problem doesn't seem to occur anymore. Let me know if it's fixed or if it's still broken

https://github.com/nickc01/WeaverCore/releases/tag/v1.1.0.0
https://github.com/nickc01/Inferno-King-Grimm/releases/tag/v4.1.0.3
https://github.com/nickc01/Corrupted-Kin/releases/tag/v1.2.0.2

**Comment by Hoo-Knows** [comment]
Just got to try it out, the camera is fixed now. Thanks for your time!
